# Server TPS below this value is considered low.
low-tps-threshold: 15.0

# If true, mob AI will be disabled during low TPS. Set to false to only disable mob spawning.
disable-mob-ai: true

# Interval (in ticks) between ground item removals.
item-clear-interval: 6000